# DO NOT EDIT THIS FILE
#
# Helpers for gotchas when calling the API

import requests

BASE_URL = "https://api.threads.dev-auth2.com/v1"

# =============================================================================
# Helpers
# =============================================================================

# Required when performing non-GET requests
def required_headers(session: requests.Session) -> dict:
    return {"x-csrftoken": session.cookies.get("csrftoken")}

# Messages must be formatted in this way before uploading
def format_message(message: str) -> str:
    return '{"blocks":[{"key":"1blqq","text":"' + message + '","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}'
    
